### ISSUE TITLE
taxonomicStatus

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#9]
taxonomicStatus has a [GBIF vocubulary](http://rs.gbif.org/vocabulary/gbif/taxonomic_status.xml). 
In WRIMS, the following terms do not match this vocubulary:

`alternate representation`
`nomen dubium`
`nomen nudum`
`taxon inquirendum`
`temporary name`
`unaccepted`
`uncertain`

Actually, only `accepted` fits the vocabulary (roughly 90% of all species). I feel that the WRIMS vocabulary for `taxonomicStatus` could no be matched with the GBIF vocabulary.

One solution for the remaining 10% would be to leave `taxonomicStatus` empty for these species, and to specify their taxonomic status under the Darwin Core term `taxonRemarks`.

**Comment by bart-v** [comment]
Yes, indeed.

Notice that some can be mapped to nomenclaturalStatus (the WRIMS status is actually a mixture of both taxon and nomenclatural status)

**Comment by peterdesmet** [comment]
@LienReysorhove, can you suggest a mapping of the current values to http://rs.gbif.org/vocabulary/gbif/taxonomic_status.xml **and** http://rs.gbif.org/vocabulary/gbif/nomenclatural_status.xml?

@bart-v: I assume the mapping to Darwin Core is done in SQL or a script? So if a theoretical mapping is provided, it can be implemented?

**Comment by bart-v** [comment]
Yes it's done via SQL and some scripting.

Notice that we don't want to loose information, so mapping it to "empty" is  really not an option at our side.
If GBIF can't handle vocab X or Y, then that's too bad...

**Comment by peterdesmet** [comment]
Ok, mapping won’t lose information, just relay to correct column

**Comment by LienReyserhove** [comment]
This is a suggestion for the mapping. I looked up the definition of the different terms and attempted a mapping to taxonomicStatus and nomenclaturalStatus

WRIMS taxonomicStatus | definition
--- | ---
unaccepted | synonym, or something that is not accepted
temporary name | Name that did not get any qualified name yet
alternate representation | an accepted name, with (or without) a subgenus, but slightly less prefered
uncertain | to indicate taxonomic or nomenclatural uncertainty for cases which cannot be classed as either 'accepted' or 'unaccepted'
nomen dubium | a name of uncertain taxonomic significance
nomen nudum | a name that does not comply with the name requirements of the codes, such as a lack of a description, diagnosis, reference to a description, diagnosis, or a type species lacking (for publications after 1999)
taxon inquirendum | of which the taxonomic validity is uncertain or disputed

This is an attempt to map the data to taxonomicStatus and nomenclaturalStatus (a = alternative term according to GBIF controlled vocabulary, when empty, I have no idea). 

WRIMS taxonomicStatus | taxonomicStatus | nomenclaturalStatus
--- | --- | ---
accepted | accepted | empty or available
unaccepted | unaccepted (a) | empty or available
temporary name |  | rejiciendumProp (?)
alternate representation | accepted | alternativum
uncertain | empty | dubimum
nomen dubium | empty | nomen dubium
nomen nudum | empty | nomen nudum
taxon inquirendum |

**Comment by LienReyserhove** [comment]
@peterdesmet, feedback requested please :grimacing:

**Comment by peterdesmet** [comment]
WRIMS taxonomicStatus | taxonomicStatus | nomenclaturalStatus
-- | -- | --
`accepted` | `accepted` | 
`unaccepted` | `synonym` (or the alternative `unaccepted`) [1] | 
`temporary name` | [8] |  [2]
`alternate representation` | `accepted` [3] | `alternativum`
`uncertain` | `doubtful` [4] | 
`nomen dubium` | [8] | `dubium` (or the alternative `nomen dubium`) [5]
`nomen nudum` | [8] | `nudum` (or the alternative `nomen nudum`) [6]
`taxon inquirendum` | [8] | `dubium` (or the alternative `nomen inquirendum`) [7]

[1]: could use `unaccepted` to stick closer to original data. Will be treated as a `synonym` when harvested.
[2]: @bart-v definition for `provisorium` is:

> Provisional name, a name proposed in anticipation of the future acceptance of the taxon concerned, or of a particular circumscription, position, or rank of the taxon (ICBN Art. 34.1).

Does that match with `temporary name`?

[3]: @bart-v I find it a bit odd that an alternative representation is defined as an `accepted name`, especially if the preferred name and the relationship between the two would be included in the dataset: is that the case? If so, I would mark these as `taxonomicStatus: synonym` rather than `accepted`, so there is only one accepted name per group of related names.
[4]: `doubtful` is not listed in the vocab (probably an oversight, see https://github.com/gbif/rs.gbif.org/issues/26) but definitely used by GBIF for taxa with uncertain status
[5]: using `nomen dubimum` to stick closer to original data. Is not yet an alternative for `dubimum` in GBIF vocab, but should be: https://github.com/gbif/rs.gbif.org/issues/28
[6]: using `nomen nudum` to stick closer to the original data. Will be treated as `nudum` when harvested.
[6]: `nomen inquirendum` to stick closer to the original data. Is not yet an alternative for `dubimum` in GBIF vocab, but should be: https://github.com/gbif/rs.gbif.org/issues/27
[8]: unclear to me if a taxonomic status should be added for these names, e.g. `informal` or `doubtful`

**Comment by qgroom** [comment]
Shouldn't we use these vocabularies?
http://rs.gbif.org/vocabulary/gbif/nomenclatural_status.xml
http://rs.gbif.org/vocabulary/gbif/taxonomic_status.xml

Therefore
unaccepted = synonym
temporary name = Do not use this name at all. It is not valid and should not be published in public.
alternativum = This has a very specific definition. If possible don't use any of these names.

Following the GBIF vocabs
nomen dubium = dubimum
nomen nudum = nudum
taxon inquirendum = dubimum [only should be used with an organism under the ICZN]

**Comment by peterdesmet** [comment]
@qgroom, those are the vocabs we are mapping to. 👌 The mapping you suggest is the same as the one I propose. 👌 Regarding not including “temporary” and “alternativum”, I guess that is up to @bart-v

**Comment by bart-v** [comment]
[2] I think mapping "temporary name" to "provisorium" is OK, if I look at the definition. Our use is slightly broader, i.e. we also give that status to all incertae sedis names, bu I guess that is OK.

[3] absolutely not: "alternative representation" is definitely "accepted" or valid (ICZN). As you know, in ICZN, creating a name "Genus (Subgenus) species" automatically creates the name "Genus species" (subgenus is optional). Thus both names are accepted and valid. 
But, for technical reasons, you can indeed say that one of both is a synonym or "less preferred": i.e. to have one accepted name per species, or to not count species twice, etc... But *displaying* it as a synonym to an end user is wrong...

**Comment by qgroom** [comment]
In the WoRMS paper below it is clear that temporary name is only used as a high taxonomy placeholder. 

> This name status can be used to create ad-hoc higher rank taxa of convenience to accommodate child
> taxa for which the classification is not yet finalised

This is rather different to a "_nomen provisorium_", which is a manuscript name for a taxon, rather than a provisional classification.

I'll have to read up on alternative names for plants, but the ICN website is currently off line. As far as I'm aware alternative names are only relevant to family names, but I will have to see what the code says.

According to the WoRMS paper it is clear their use of "alternative representation" is not the same as "_nomen alternativum_". What alternative representation means in WoRMS is that there is no taxonomic consensus on which name is the accepted name. However, as only one name can be accepted in WoRMS the alternative name is a genuine synonym. I'm not sure why @bart-v says it shouldn't be displayed as a synonym. Perhaps, it keeps taxonomists from complaining that their taxonomy is not followed.

Horton, T., Gofas, S., Kroh, A., Poore, G. C., Read, G., Rosenberg, G., ... & Costello, M. J. (2017). Improving nomenclatural consistency: a decade of experience in the World Register of Marine Species. European Journal of Taxonomy, (389). http://nora.nerc.ac.uk/id/eprint/518983/1/512-2513-1-PB.pdf

**Comment by bart-v** [comment]
It looks like in WRIMS, "temporary name" is indeed only used for ad-hoc higher rank taxa indeed. And only for 18 cases
http://www.marinespecies.org/introduced/aphia.php?p=taxlist&vOnly=7&action=search&adv=1
So better not to map it, and move on :)

About "alternate representation": best to explain it with an example:
http://www.marinespecies.org/introduced/aphia.php?p=taxdetails&id=473148
- Rhinoclavis (Proclava) kochi (Philippi, 1848) is valid (ICZN)
- Rhinoclavis kochi (Philippi, 1848) is valid (ICZN)

None of them is a synonym according to ICZN: both may be used.
http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=&article=43#1
43.1. Statement of the Principle of Coordination applied to genus-group names. A name established for a taxon at either rank in the genus group is deemed to have been simultaneously established by the same author for a nominal taxon at the other rank in the group; both nominal taxa have the same type species

**Comment by LienReyserhove** [comment]
So, can I conclude the following with respect to the [suggested mapping](https://github.com/trias-project/wrims-checklist/issues/9#issuecomment-459768273):

- OK for: `accepted`, `unaccepted`, `uncertain`, `nomen dubium`, `nomen nudum`, `taxon inquirendum`
- `temporary name`: leave empty for both fields (only 18 cases in the checklist)
- `alternate representation`: I'm not a taxonomist, but what I can deduct from the arguments of @bart-v , is that both scientificnames in the abovementioned example can indeed be considered as accepted. So the mapping by @peterdesmet for this term is correct

**Comment by LienReyserhove** [comment]
To be clear about the requested changes, and proceeding on my latest comment in this issue, I copied the table from @peterdesmet here as a final suggestion for the next WRIMS export:

WRIMS taxonomicStatus | taxonomicStatus | nomenclaturalStatus
-- | -- | --
`accepted` | `accepted` | 
`unaccepted` | `synonym` (or the alternative `unaccepted`) | 
`temporary name` |  |  
`alternate representation` | `accepted` | `alternativum`
`uncertain` | `doubtful`  | 
`nomen dubium` |  | `dubium` (or the alternative `nomen dubium`)
`nomen nudum` |  | `nudum` (or the alternative `nomen nudum`) 
`taxon inquirendum` |  | `dubium` (or the alternative `nomen inquirendum`)

**Comment by bart-v** [comment]
Implemented, will be available in the next export 2019-05-01
